#!/bin/sh
set -e

ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.bash_profile" "$HOME/.bash_profile"
ln -sf "$PWD/scripts" "$HOME/Scripts"

chmod +x $HOME/Scripts/*

mkdir -p "$HOME/.local/bin" || true
# vim setup
cd vim && ./setup
cd - > /dev/null

# tmux setup
cd tmux && ./setup
cd - > /dev/null
